states = [
    {"value": "AL", "text": "Alabama"},
    {"value": "AK", "text": "Alaska"},
    {"value": "AZ", "text": "Arizona"},
    {"value": "AR", "text": "Arkansas"},
    {"value": "CA", "text": "California"},
    {"value": "CO", "text": "Colorado"},
    {"value": "CT", "text": "Connecticut"},
    {"value": "DE", "text": "Delaware"},
    {"value": "FL", "text": "Florida"},
    {"value": "GA", "text": "Georgia"},
    {"value": "HI", "text": "Hawaii"},
    {"value": "ID", "text": "Idaho"},
    {"value": "IL", "text": "Illinois"},
    {"value": "IN", "text": "Indiana"},
    {"value": "IA", "text": "Iowa"},
    {"value": "KS", "text": "Kansas"},
    {"value": "KY", "text": "Kentucky"},
    {"value": "LA", "text": "Louisiana"},
    {"value": "ME", "text": "Maine"},
    {"value": "MD", "text": "Maryland"},
    {"value": "MA", "text": "Massachusetts"},
    {"value": "MI", "text": "Michigan"},
    {"value": "MN", "text": "Minnesota"},
    {"value": "MS", "text": "Mississippi"},
    {"value": "MO", "text": "Missouri"},
    {"value": "MT", "text": "Montana"},
    {"value": "NE", "text": "Nebraska"},
    {"value": "NV", "text": "Nevada"},
    {"value": "NH", "text": "New Hampshire"},
    {"value": "NJ", "text": "New Jersey"},
    {"value": "NM", "text": "New Mexico"},
    {"value": "NY", "text": "New York"},
    {"value": "NC", "text": "North Carolina"},
    {"value": "ND", "text": "North Dakota"},
    {"value": "OH", "text": "Ohio"},
    {"value": "OK", "text": "Oklahoma"},
    {"value": "OR", "text": "Oregon"},
    {"value": "PA", "text": "Pennsylvania"},
    {"value": "RI", "text": "Rhode Island"},
    {"value": "SC", "text": "South Carolina"},
    {"value": "SD", "text": "South Dakota"},
    {"value": "TN", "text": "Tennessee"},
    {"value": "TX", "text": "Texas"},
    {"value": "UT", "text": "Utah"},
    {"value": "VT", "text": "Vermont"},
    {"value": "VA", "text": "Virginia"},
    {"value": "WA", "text": "Washington"},
    {"value": "WV", "text": "West Virginia"},
    {"value": "WI", "text": "Wisconsin"},
    {"value": "WY", "text": "Wyoming"}
]
countries = [
    {"value": "AF", "text": "Afghanistan"},
    {"value": "AL", "text": "Albania"},
    {"value": "DZ", "text": "Algeria"},
    {"value": "AS", "text": "American Samoa"},
    {"value": "AD", "text": "Andorra"},
    {"value": "AO", "text": "Angola"},
    {"value": "AI", "text": "Anguilla"},
    {"value": "AG", "text": "Antigua and Barbuda"},
    {"value": "AR", "text": "Argentina"},
    {"value": "AM", "text": "Armenia"},
    {"value": "AW", "text": "Aruba"},
    {"value": "AU", "text": "Australia"},
    {"value": "AT", "text": "Austria"},
    {"value": "AZ", "text": "Azerbaijan"},
    {"value": "BS", "text": "Bahamas"},
    {"value": "BH", "text": "Bahrain"},
    {"value": "BD", "text": "Bangladesh"},
    {"value": "BB", "text": "Barbados"},
    {"value": "BY", "text": "Belarus"},
    {"value": "BE", "text": "Belgium"},
    {"value": "BZ", "text": "Belize"},
    {"value": "BJ", "text": "Benin"},
    {"value": "BM", "text": "Bermuda"},
    {"value": "BT", "text": "Bhutan"},
    {"value": "BO", "text": "Bolivia"},
    {"value": "BA", "text": "Bosnia and Herzegovina"},
    {"value": "BW", "text": "Botswana"},
    {"value": "BR", "text": "Brazil"},
    {"value": "IO", "text": "British Indian Ocean Territory"},
    {"value": "BN", "text": "Brunei Darussalam"},
    {"value": "BG", "text": "Bulgaria"},
    {"value": "BF", "text": "Burkina Faso"},
    {"value": "BI", "text": "Burundi"},
    {"value": "KH", "text": "Cambodia"},
    {"value": "CM", "text": "Cameroon"},
    {"value": "CA", "text": "Canada"},
    {"value": "CV", "text": "Cape Verde"},
    {"value": "KY", "text": "Cayman Islands"},
    {"value": "CF", "text": "Central African Republic"},
    {"value": "TD", "text": "Chad"},
    {"value": "CL", "text": "Chile"},
    {"value": "CN", "text": "China"},
    {"value": "CX", "text": "Christmas Island"},
    {"value": "CC", "text": "Cocos (Keeling) Islands"},
    {"value": "CO", "text": "Colombia"},
    {"value": "KM", "text": "Comoros"},
    {"value": "CG", "text": "Congo"},
    {"value": "CD", "text": "Congo, The Democratic Republic of the"},
    {"value": "CK", "text": "Cook Islands"},
    {"value": "CR", "text": "Costa Rica"},
    {"value": "CI", "text": "Cote D'Ivoire"},
    {"value": "HR", "text": "Croatia"},
    {"value": "CU", "text": "Cuba"},
    {"value": "CY", "text": "Cyprus"},
    {"value": "CZ", "text": "Czech Republic"},
    {"value": "DK", "text": "Denmark"},
    {"value": "DJ", "text": "Djibouti"},
    {"value": "DM", "text": "Dominica"},
    {"value": "DO", "text": "Dominican Republic"},
    {"value": "EC", "text": "Ecuador"},
    {"value": "EG", "text": "Egypt"},
    {"value": "SV", "text": "El Salvador"},
    {"value": "GQ", "text": "Equatorial Guinea"},
    {"value": "ER", "text": "Eritrea"},
    {"value": "EE", "text": "Estonia"},
    {"value": "ET", "text": "Ethiopia"},
    {"value": "FK", "text": "Falkland Islands (Malvinas)"},
    {"value": "FO", "text": "Faroe Islands"},
    {"value": "FJ", "text": "Fiji"},
    {"value": "FI", "text": "Finland"},
    {"value": "FR", "text": "France"},
    {"value": "GF", "text": "French Guiana"},
    {"value": "PF", "text": "French Polynesia"},
    {"value": "TF", "text": "French Southern Territories"},
    {"value": "GA", "text": "Gabon"},
    {"value": "GM", "text": "Gambia"},
    {"value": "GE", "text": "Georgia"},
    {"value": "DE", "text": "Germany"},
    {"value": "GH", "text": "Ghana"},
    {"value": "GI", "text": "Gibraltar"},
    {"value": "GR", "text": "Greece"},
    {"value": "GL", "text": "Greenland"},
    {"value": "GD", "text": "Grenada"},
    {"value": "GP", "text": "Guadeloupe"},
    {"value": "GU", "text": "Guam"},
    {"value": "GT", "text": "Guatemala"},
    {"value": "GN", "text": "Guinea"},
    {"value": "GW", "text": "Guinea-Bissau"},
    {"value": "GY", "text": "Guyana"},
    {"value": "HT", "text": "Haiti"},
    {"value": "HM", "text": "Heard Island and Mcdonald Islands"},
    {"value": "VA", "text": "Holy See (Vatican City State)"},
    {"value": "HN", "text": "Honduras"},
    {"value": "HK", "text": "Hong Kong"},
    {"value": "HU", "text": "Hungary"},
    {"value": "IS", "text": "Iceland"},
    {"value": "IN", "text": "India"},
    {"value": "ID", "text": "Indonesia"},
    {"value": "IR", "text": "Iran, Islamic Republic Of"},
    {"value": "IQ", "text": "Iraq"},
    {"value": "IE", "text": "Ireland"},
    {"value": "IL", "text": "Israel"},
    {"value": "IT", "text": "Italy"},
    {"value": "JM", "text": "Jamaica"},
    {"value": "JP", "text": "Japan"},
    {"value": "JO", "text": "Jordan"},
    {"value": "KZ", "text": "Kazakhstan"},
    {"value": "KE", "text": "Kenya"},
    {"value": "KI", "text": "Kiribati"},
    {"value": "KP", "text": "Korea, Democratic People'S Republic of"},
    {"value": "KR", "text": "Korea, Republic of"},
    {"value": "KW", "text": "Kuwait"},
    {"value": "KG", "text": "Kyrgyzstan"},
    {"value": "LA", "text": "Lao People'S Democratic Republic"},
    {"value": "LV", "text": "Latvia"},
    {"value": "LB", "text": "Lebanon"},
    {"value": "LS", "text": "Lesotho"},
    {"value": "LR", "text": "Liberia"},
    {"value": "LY", "text": "Libyan Arab Jamahiriya"},
    {"value": "LI", "text": "Liechtenstein"},
    {"value": "LT", "text": "Lithuania"},
    {"value": "LU", "text": "Luxembourg"},
    {"value": "MO", "text": "Macao"},
    {"value": "MK", "text": "Macedonia, The Former Yugoslav Republic of"},
    {"value": "MG", "text": "Madagascar"},
    {"value": "MW", "text": "Malawi"},
    {"value": "MY", "text": "Malaysia"},
    {"value": "MV", "text": "Maldives"},
    {"value": "ML", "text": "Mali"},
    {"value": "MT", "text": "Malta"},
    {"value": "MH", "text": "Marshall Islands"},
    {"value": "MQ", "text": "Martinique"},
    {"value": "MR", "text": "Mauritania"},
    {"value": "MU", "text": "Mauritius"},
    {"value": "YT", "text": "Mayotte"},
    {"value": "MX", "text": "Mexico"},
    {"value": "FM", "text": "Micronesia, Federated States of"},
    {"value": "MD", "text": "Moldova, Republic of"},
    {"value": "MC", "text": "Monaco"},
    {"value": "MN", "text": "Mongolia"},
    {"value": "MS", "text": "Montserrat"},
    {"value": "MA", "text": "Morocco"},
    {"value": "MZ", "text": "Mozambique"},
    {"value": "MM", "text": "Myanmar"},
    {"value": "NA", "text": "Namibia"},
    {"value": "NR", "text": "Nauru"},
    {"value": "NP", "text": "Nepal"},
    {"value": "NL", "text": "Netherlands"},
    {"value": "AN", "text": "Netherlands Antilles"},
    {"value": "NC", "text": "New Caledonia"},
    {"value": "NZ", "text": "New Zealand"},
    {"value": "NI", "text": "Nicaragua"},
    {"value": "NE", "text": "Niger"},
    {"value": "NG", "text": "Nigeria"},
    {"value": "NU", "text": "Niue"},
    {"value": "NF", "text": "Norfolk Island"},
    {"value": "MP", "text": "Northern Mariana Islands"},
    {"value": "NO", "text": "Norway"},
    {"value": "OM", "text": "Oman"},
    {"value": "PK", "text": "Pakistan"},
    {"value": "PW", "text": "Palau"},
    {"value": "PS", "text": "Palestinian Territory, Occupied"},
    {"value": "PA", "text": "Panama"},
    {"value": "PG", "text": "Papua New Guinea"},
    {"value": "PY", "text": "Paraguay"},
    {"value": "PE", "text": "Peru"},
    {"value": "PH", "text": "Philippines"},
    {"value": "PN", "text": "Pitcairn"},
    {"value": "PL", "text": "Poland"},
    {"value": "PT", "text": "Portugal"},
    {"value": "PR", "text": "Puerto Rico"},
    {"value": "QA", "text": "Qatar"},
    {"value": "RE", "text": "Reunion"},
    {"value": "RO", "text": "Romania"},
    {"value": "RU", "text": "Russian Federation"},
    {"value": "RW", "text": "Rwanda"},
    {"value": "SH", "text": "Saint Helena"},
    {"value": "KN", "text": "Saint Kitts and Nevis"},
    {"value": "LC", "text": "Saint Lucia"},
    {"value": "PM", "text": "Saint Pierre and Miquelon"},
    {"value": "VC", "text": "Saint Vincent and the Grenadines"},
    {"value": "WS", "text": "Samoa"},
    {"value": "SM", "text": "San Marino"},
    {"value": "ST", "text": "Sao Tome and Principe"},
    {"value": "SA", "text": "Saudi Arabia"},
    {"value": "SN", "text": "Senegal"},
    {"value": "CS", "text": "Serbia and Montenegro"},
    {"value": "SC", "text": "Seychelles"},
    {"value": "SL", "text": "Sierra Leone"},
    {"value": "SG", "text": "Singapore"},
    {"value": "SK", "text": "Slovakia"},
    {"value": "SI", "text": "Slovenia"},
    {"value": "SB", "text": "Solomon Islands"},
    {"value": "SO", "text": "Somalia"},
    {"value": "ZA", "text": "South Africa"},
    {"value": "GS", "text": "South Georgia and the South Sandwich Islands"},
    {"value": "ES", "text": "Spain"},
    {"value": "LK", "text": "Sri Lanka"},
    {"value": "SD", "text": "Sudan"},
    {"value": "SR", "text": "Suriname"},
    {"value": "SJ", "text": "Svalbard and Jan Mayen"},
    {"value": "SZ", "text": "Swaziland"},
    {"value": "SE", "text": "Sweden"},
    {"value": "CH", "text": "Switzerland"},
    {"value": "SY", "text": "Syrian Arab Republic"},
    {"value": "TW", "text": "Taiwan, Province of China"},
    {"value": "TJ", "text": "Tajikistan"},
    {"value": "TZ", "text": "Tanzania, United Republic of"},
    {"value": "TH", "text": "Thailand"},
    {"value": "TL", "text": "Timor-Leste"},
    {"value": "TG", "text": "Togo"},
    {"value": "TK", "text": "Tokelau"},
    {"value": "TO", "text": "Tonga"},
    {"value": "TT", "text": "Trinidad and Tobago"},
    {"value": "TN", "text": "Tunisia"},
    {"value": "TR", "text": "Turkey"},
    {"value": "TM", "text": "Turkmenistan"},
    {"value": "TC", "text": "Turks and Caicos Islands"},
    {"value": "TV", "text": "Tuvalu"},
    {"value": "UG", "text": "Uganda"},
    {"value": "UA", "text": "Ukraine"},
    {"value": "AE", "text": "United Arab Emirates"},
    {"value": "GB", "text": "United Kingdom"},
    {"value": "US", "text": "United States"},
    {"value": "UM", "text": "United States Minor Outlying Islands"},
    {"value": "UY", "text": "Uruguay"},
    {"value": "UZ", "text": "Uzbekistan"},
    {"value": "VU", "text": "Vanuatu"},
    {"value": "VE", "text": "Venezuela"},
    {"value": "VN", "text": "Viet Nam"},
    {"value": "VG", "text": "Virgin Islands, British"},
    {"value": "VI", "text": "Virgin Islands, U.S."},
    {"value": "WF", "text": "Wallis and Futuna"},
    {"value": "EH", "text": "Western Sahara"},
    {"value": "YE", "text": "Yemen"},
    {"value": "ZM", "text": "Zambia"},
    {"value": "ZW", "text": "Zimbabwe"}
]

yes_no_na = [
    {"value": "Y", "text": "YES"},
    {"value": "N", "text": "NO"},
    {"value": "A", "text": "N/A"}
]

classtypes = [
    {"value": "a", "text": "United States - Class A", "default": True},
    {"value": "b", "text": "United States - Class B", "default": False},
    {"value": "c", "text": "United States - Class C", "default": False},
    {"value": "n", "text": "United States - Non-CDL", "default": False},
    {"value": "ab-1", "text": "Alberta - Class 1", "default": False},
    {"value": "ab-2", "text": "Alberta - Class 2", "default": False},
    {"value": "ab-3", "text": "Alberta - Class 3", "default": False},
    {"value": "ab-4", "text": "Alberta - Class 4", "default": False},
    {"value": "ab-n", "text": "Alberta - Non-CDL", "default": False},
    {"value": "bc-1", "text": "British Columbia - Class 1", "default": False},
    {"value": "bc-2", "text": "British Columbia - Class 2", "default": False},
    {"value": "bc-3", "text": "British Columbia - Class 3", "default": False},
    {"value": "bc-4u", "text": "British Columbia - Class 4 Unrestricted", "default": False},
    {"value": "bc-4r", "text": "British Columbia - Class 4 Restricted", "default": False},
    {"value": "bc-n", "text": "British Columbia - Non-CDL", "default": False},
    {"value": "mb-1", "text": "Manitoba - Class 1", "default": False},
    {"value": "mb-2", "text": "Manitoba - Class 2", "default": False},
    {"value": "mb-3", "text": "Manitoba - Class 3", "default": False},
    {"value": "mb-4", "text": "Manitoba - Class 4", "default": False},
    {"value": "mb-n", "text": "Manitoba - Non-CDL", "default": False},
    {"value": "nb-1", "text": "New Brunswick - Class 1", "default": False},
    {"value": "nb-2", "text": "New Brunswick - Class 2", "default": False},
    {"value": "nb-3", "text": "New Brunswick - Class 3", "default": False},
    {"value": "nb-3-4", "text": "New Brunswick - Class 3 & 4", "default": False},
    {"value": "nb-4", "text": "New Brunswick - Class 4", "default": False},
    {"value": "nb-5", "text": "New Brunswick - Class 5", "default": False},
    {"value": "nb-n", "text": "New Brunswick - Non-CDL", "default": False},
    {"value": "nl-1", "text": "Newfoundland Labrador - Class 1", "default": False},
    {"value": "nl-2", "text": "Newfoundland Labrador - Class 2", "default": False},
    {"value": "nl-3", "text": "Newfoundland Labrador - Class 3", "default": False},
    {"value": "nl-4", "text": "Newfoundland Labrador - Class 4", "default": False},
    {"value": "nl-n", "text": "Newfoundland Labrador - Non-CDL", "default": False},
    {"value": "nt-1", "text": "Northwest Territories - Class 1", "default": False},
    {"value": "nt-2", "text": "Northwest Territories - Class 2", "default": False},
    {"value": "nt-3", "text": "Northwest Territories - Class 3", "default": False},
    {"value": "nt-4", "text": "Northwest Territories - Class 4", "default": False},
    {"value": "nt-n", "text": "Northwest Territories - Non-CDL", "default": False},
    {"value": "ns-1", "text": "Nova Scotia - Class 1", "default": False},
    {"value": "ns-2", "text": "Nova Scotia - Class 2", "default": False},
    {"value": "ns-3", "text": "Nova Scotia - Class 3", "default": False},
    {"value": "ns-4", "text": "Nova Scotia - Class 4", "default": False},
    {"value": "ns-n", "text": "Nova Scotia - Non-CDL", "default": False},
    {"value": "nu-1", "text": "Nunavut - Class 1", "default": False},
    {"value": "nu-2", "text": "Nunavut - Class 2", "default": False},
    {"value": "nu-3", "text": "Nunavut - Class 3", "default": False},
    {"value": "nu-4", "text": "Nunavut - Class 4", "default": False},
    {"value": "nu-n", "text": "Nunavut - Non-CDL", "default": False},
    {"value": "on-a", "text": "Ontario - Class A", "default": False},
    {"value": "on-b", "text": "Ontario - Class B", "default": False},
    {"value": "on-c", "text": "Ontario - Class C", "default": False},
    {"value": "on-d", "text": "Ontario - Class D", "default": False},
    {"value": "on-e", "text": "Ontario - Class E", "default": False},
    {"value": "on-f", "text": "Ontario - Class F", "default": False},
    {"value": "on-n", "text": "Ontario - Non-CDL", "default": False},
    {"value": "pe-1", "text": "Prince Edward Island - Class 1", "default": False},
    {"value": "pe-2", "text": "Prince Edward Island - Class 2", "default": False},
    {"value": "pe-3", "text": "Prince Edward Island - Class 3", "default": False},
    {"value": "pe-4", "text": "Prince Edward Island - Class 4", "default": False},
    {"value": "pe-n", "text": "Prince Edward Island - Non-CDL", "default": False},
    {"value": "qc-1", "text": "Quebec - Class 1", "default": False},
    {"value": "qc-2", "text": "Quebec - Class 2", "default": False},
    {"value": "qc-3", "text": "Quebec - Class 3", "default": False},
    {"value": "qc-4a", "text": "Quebec - Class 4A", "default": False},
    {"value": "qc-4b", "text": "Quebec - Class 4B", "default": False},
    {"value": "qc-4c", "text": "Quebec - Class 4C", "default": False},
    {"value": "qc-n", "text": "Quebec - Non-CDL", "default": False},
    {"value": "sk-1", "text": "Saskatchewan - Class 1", "default": False},
    {"value": "sk-2", "text": "Saskatchewan - Class 2", "default": False},
    {"value": "sk-3", "text": "Saskatchewan - Class 3", "default": False},
    {"value": "sk-4", "text": "Saskatchewan - Class 4", "default": False},
    {"value": "sk-n", "text": "Saskatchewan - Non-CDL", "default": False},
    {"value": "yt-1", "text": "Yukon - Class 1", "default": False},
    {"value": "yt-2", "text": "Yukon - Class 2", "default": False},
    {"value": "yt-3", "text": "Yukon - Class 3", "default": False},
    {"value": "yt-4", "text": "Yukon - Class 4", "default": False},
    {"value": "yt-n", "text": "Yukon - Non-CDL", "default": False},
    {"value": "mx-b", "text": "Mexico - Type B", "default": False},
    {"value": "mx-n", "text": "Mexico - Non-CDL", "default": False},
    {"value": "other", "text": "Other", "default": False}
]

referenceTypes = {
    "socialsecurity": 0
}
